FROM node:20.13.1-alpine

WORKDIR /app

# Install dependencies
COPY package.json package-lock.json ./
RUN npm install -f

# Copy source code
COPY . .

EXPOSE 3000

# Run the development server
CMD ["npm", "run", "dev"]